### PR TITLE
Improved locking performance on .NET 9.0+

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**

### CODE REVIEW

**Comment by mjfreelancing** [comment]
I currently have another active branch dedicated to NET 9, and this will include a review of locking updates based on the new `Lock` provided with NET 9. Since NET 9 is not yet released, I will not be making these changes to the stable v7.x releases.

The AllOverIt v8 branch (for NET 8 and NET 9 only since NET 6 will not be supported when NET 9 is released) can be found here: https://github.com/mjfreelancing/AllOverIt/tree/v8.0-NET9 

I will review your PR content when I apply my updates. I'm currently adding new tests, but locking is the next main item on my TODO list.

**Comment by MarkCiliaVincenti** [comment]
OK let me know if you need anything from my end.

**Comment by mjfreelancing** [comment]
@MarkCiliaVincenti After a review of the existing code, there's only two locks that required attention. I have elected to conditionally apply Lock based on NET 9 or not. This will all be simplified when NET 8 is no longer supported and I would prefer to not bring in any additional dependencies unless absolutely required. Thanks for your interest nonetheless.

**Comment by mjfreelancing** [comment]
I've made all the changes that I require in my latest version, thanks.

**Pull request closed without merging**
